server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ashfak777/microservices-config-store-one
          default-label: main
          search-paths:
            - '*service'
